[package]
name = "clumsy"
version = "0.1.0"
edition = "2021"

[dependencies]
# Rust bindings for the WinDivert library, enabling packet capture and modification on Windows.
windivert = { version = "0.6", features = ["vendored"] }
# Library for generating random numbers, used for probabilistic operations.
rand = "0.9.0-alpha.2"