name: Rust

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build-linux:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Install dependencies
        run: sudo apt-get update && sudo apt-get install -y pkg-config libssl-dev
      - name: Build (Linux)
        run: cargo build --verbose --all-targets
      - name: Run tests (Linux)
        run: cargo test --verbose --all-targets

  build-windows:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Rust
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          target: x86_64-pc-windows-msvc
          override: true
      - name: Install dependencies
        run: choco install windivert
      - name: Build (Windows)
        run: cargo build --verbose --all-targets
      - name: Run tests (Windows)
        run: cargo test --verbose --all-targets